#
#~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth:ignoredups:erasedups # 历史命令增强 

# append to the history file, don't overwrite it
shopt -s histappend

export HISTIGNORE=”history:cd:exit:ls:pwd:man”
# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000000
HISTFILESIZE=2000000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
#[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
#force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	# We have color support; assume it's compliant with Ecma-48
	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
	# a case would tend to support setf rather than setaf.)
	color_prompt=yes
    else
	color_prompt=
    fi
fi

if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias dir='dir --color=auto'
    alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

function say {
    mpv http://dict.youdao.com/dictvoice?audio=${1}'&'type=1 > /dev/null
    }

alias say='say $1'
alias vi='vim'
alias   q="exit"
alias   c="clear"
alias   ls="ls -h --color --time-style '+%Y/%m/%d %H:%M:%S'"
alias commit="git commit -a -m "
alias push="git push origin master"
alias   up="sudo apt-get update && sudo apt-get dist-upgrade && sudo apt-get autoremove;" # sudo flatpak update; sudo flatpak uninstall --unused
alias   rm="rm -i"
alias lunar="lunar -u"
alias cpr='rsync -rltgoDh --info=progress2'
alias rsmv='rsync -a  --info=progress2 --remove-source-files'
alias cgrep='grep -Rn --color'
alias grep='grep --color'
alias md2a4report=" pandoc -s --pdf-engine=xelatex --highlight-style=tango -F pandoc-citeproc --dpi=300 -V CJKmainfont='WenQuanYi Micro Hei' -V fontsize=11pt -V documentclass=scrreprt -V papersize=a4"
alias md2b5report=" pandoc -s --pdf-engine=xelatex --highlight-style=tango -F pandoc-citeproc --dpi=300 -V CJKmainfont='WenQuanYi Micro Hei' -V fontsize=11pt -V documentclass=scrreprt -V papersize=b5"
alias md2a5report=" pandoc -s --pdf-engine=xelatex --highlight-style=tango -F pandoc-citeproc --dpi=300 -V CJKmainfont='WenQuanYi Micro Hei' -V fontsize=11pt -V documentclass=scrreprt -V papersize=a5"
alias pip3up="pip3 freeze --local | grep -v '^\-e' | cut -d = -f 1  | xargs pip3 install -U"
alias dos2unixall="find . -type f -exec dos2unix {} \;"
alias unix2dosall="find . -type f -exec unix2dos {} \;"

#cd() { builtin cd "$@" && ls -ltrha; }
alias du='du --max-depth=1'

# Install Ruby Gems to ~/gems' >> ~/.bashrc
export GEM_HOME="$HOME/.gems"
export PATH="$HOME/.gems/bin:$PATH"

#export LANG=en_US.UTF-8

# alias for ftp
alias ftpEpn="lftp -u anonymous,passwd -e \"set ftp:ssl-allow yes\"   ftp.epncb.oma.be:/pub/data/format/ "
alias ftpEsa="lftp -u anonymous,passwd -e \"set ftp:ssl-allow yes\"   gssc.esa.int                       "
alias ftpHkc="lftp -u anonymous,passwd -e \"set ftp:ssl-allow yes;set ssl:verify-certificate no\"   ftp.geodetic.gov.hk                "
alias ftpIgn="lftp -u anonymous,passwd -e \"set ftp:ssl-allow yes\"   igs.ign.fr                         "
alias ftpUnv="lftp -u anonymous,passwd -e \"set ftp:ssl-allow yes\"   data-out.unavco.org                "
alias ftpWhu="lftp -u anonymous,passwd -e \"set ftp:ssl-allow yes\"   igs.gnsswhu.cn                     "
alias ftpBkg="lftp -u anonymous,passwd -e \"set ftp:ssl-allow yes\"   igs-ftp.bkg.bund.de                    "
alias ftpAus="lftp -u anonymous,passwd -e \"set ftp:ssl-allow yes\"   ftp.ga.gov.au                      "
alias ftpNas="lftp -u anonymous,passwd -e \"set ftp:ssl-force yes\"   gdc.cddis.eosdis.nasa.gov          "

PS1=""
PS1+="\[\033[1;32m\][${debian_chroot:+($debian_chroot)}\u@\h]\[\e[0m\]"

PATH=$PATH:/opt/bin/:~/.local/bin/:/usr/local/lib

PS1+="\[\033[1;35m\][\w]\[\e[0m\]"

function git_branch {
    ref=$(git symbolic-ref HEAD 2> /dev/null) || return;
    branch="${ref#refs/heads/}"

    # 检查是否有修改
    if git diff --quiet 2>/dev/null && git diff --cached --quiet 2>/dev/null && [ -z "$(git ls-files --others --exclude-standard)" ]; then
        echo "(${branch})"
    else
        echo "(${branch}*)"
    fi
}

if command -v git 1>/dev/null 2>&1; then
    PS1+="\[\033[1;33m\]\$(git_branch)\[\e[0m\]"
fi

PS1+="\[\033[1;32m\]$: \[\e[0m\]"

export PATH="$HOME/.local/bin/:$PATH"

